version: "3.4"
services:
    db:
        image: kapocris/countingstringsdb        
        networks:
            - new
        volumes:
            - ms-sqlserver-data:/var/opt/mssql
    rabbitmq:
        image: "rabbitmq:3-management" 
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - new 
        depends_on: 
            - db
        
    countingstrings.service:
        image: kapocris/countingstringsservice
        networks:
            - new
        depends_on:
            - rabbitmq
            - db 
    countingstrings.worker:
        image: kapocris/countingstringsworker        
        networks:
            - new
        depends_on: 
            - rabbitmq
            - db             
        
    countingstrings.api:
        image: kapocris/countingstringsapi
        ports:
            - "8000:80"
        networks:
            - new
        depends_on:
            - rabbitmq
            - db
networks:
    new:
volumes:
    ms-sqlserver-data:
        driver: local 

