version: "3.4"
services:
    countingstrings.api:
        image: ${DOCKER_REGISTRY}countingstringsapi
        build:
            context: .
            dockerfile: CountingStrings.API/Dockerfile
        networks:
            - new
        depends_on:
            - rabbitmq
            - db
    rabbitmq:
        image: "rabbitmq:3-management" 
        ports:
            - "15672:15672" 
        networks:
            - new 
        depends_on:
            - db
    countingstrings.service:
        image: ${DOCKER_REGISTRY}countingstringsservice
        build:
            context: .
            dockerfile: CountingStrings.Service/Dockerfile
        networks:
            - new
        depends_on:
            - rabbitmq
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        networks:
            - new
        environment:
            SA_PASSWORD: "p@ssw0rd"
            ACCEPT_EULA: "Y"
        volumes:
            - ms-sqlserver-data:/var/opt/mssql
networks:
    new:
volumes:
    ms-sqlserver-data:
        driver: local
