version: "3.4"
services:
    countingstrings.api:
        image: ${DOCKER_REGISTRY}countingstringsapi
        build:
            context: .
            dockerfile: CountingStrings.API/Dockerfile
        env_file:
            - 'variables.env'
        networks:
            - new
        depends_on:
            - rabbitmq
            - db
    rabbitmq:
        image: "rabbitmq:3-management" 
        ports:
            - "15672:15672" 
        networks:
            - new 
        depends_on: 
            - db
    countingstrings.service:
        image: ${DOCKER_REGISTRY}countingstringsservice
        build:
            context: .
            dockerfile: CountingStrings.Service/Dockerfile
        env_file:
            - 'variables.env' 
        networks:
            - new
        depends_on:
            - rabbitmq
            - db 
    db:
        image: ${DOCKER_REGISTRY}countingstringsdb
        build:
            context: ./CountingStrings.DB
            dockerfile: Dockerfile
        networks:
            - new
        volumes:
            - ms-sqlserver-data-v2:/var/opt/mssql
networks:
    new:
volumes:
    ms-sqlserver-data-v2:
        driver: local 