acceptEula:
  value: "n"
edition:
  value: Express
collation: SQL_Latin1_General_CP1_CI_AS
lcid: 1033
hadr: 0
image:
  pullPolicy: Always
service:
  # If headless is set to TRUE then the service type is ignored
  headless: false
  type: ClusterIP
  port: 1433
  annotations: {}
deployment:
  annotations: {}
persistence:
  enabled: false
  # existingDataClaim: countingstringsdb-data
  # existingTransactionLogClaim:
  # existingBackupClaim:
  # existingMasterClaim:
  # storageClass: "-"
  # dataAccessMode: ReadWriteOnce
  # dataSize: 1Gi
  # transactionLogAccessMode: ReadWriteOnce
  # transactionLogSize: 1Gi
  # backupAccessMode: ReadWriteOnce
  # backupSize: 1Gi
  # masterAccessMode: ReadWriteOnce
  # masterSize: 1Gi
livenessprobe:
  initialDelaySeconds: 15
  periodSeconds: 20
readinessprobe:
  initialDelaySeconds: 5
  periodSeconds: 10
resources:
  limits:
  #  cpu: 100m
    memory: 2Gi
  # requests:
  #  cpu: 100m
  #  memory: 2Gi
nodeSelector: {}
  # kubernetes.io/hostname: minikube
