kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: countingstringsdb-data
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi