name: countingstringsbroker
version: 1.0.0
appVersion: 3.7.12
description: CountingStrings Broker
keywords:
- rabbitmq
- message queue
- AMQP
home: https://www.rabbitmq.com
icon: https://bitnami.com/assets/stacks/rabbitmq/img/rabbitmq-stack-220x234.png
sources:
- https://github.com/bitnami/bitnami-docker-rabbitmq
maintainers:
- name: Cristian
  email: crperez.informatica@gmail.com
engine: gotpl
