{{- if .Values.ingress.enabled -}}
{{- $fullName := include "countingstringsapi.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: countingstringsapi-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $servicePort }}
{{- end }}
